"""first bank database model

Revision ID: 1cb560e008b
Revises: None
Create Date: 2014-11-23 20:54:10.521742

"""

# revision identifiers, used by Alembic.
revision = '1cb560e008b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('less_taxable_benefits', sa.Float(), nullable=False),
    sa.Column('total_gross', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('government_pension', sa.Float(), nullable=False),
    sa.Column('federal_tax', sa.Float(), nullable=False),
    sa.Column('qpip', sa.Float(), nullable=False),
    sa.Column('employment_insurance_contriution', sa.Float(), nullable=False),
    sa.Column('provencial_tax', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_statement_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('company_name', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ytd_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ytd_hours', sa.Float(), nullable=False),
    sa.Column('ytd_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ytd_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('government_pension', sa.Float(), nullable=False),
    sa.Column('federal_tax', sa.Float(), nullable=False),
    sa.Column('qpip', sa.Float(), nullable=False),
    sa.Column('employment_insurance_contriution', sa.Float(), nullable=False),
    sa.Column('provencial_tax', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_ytd_id', sa.Integer(), nullable=False),
    sa.Column('earnings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['earnings_id'], ['earnings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['earnings_ytd_id'], ['ytd_earnings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'earnings_ytd_id', 'earnings_id')
    )
    op.create_table('deductions_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deductions_ytd_id', sa.Integer(), nullable=False),
    sa.Column('deductions_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deductions_id'], ['deductions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deductions_ytd_id'], ['ytd_deductions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'deductions_ytd_id', 'deductions_id')
    )
    op.create_table('earnings_deductions_association',
    sa.Column('earnings_association_id', sa.Integer(), nullable=False),
    sa.Column('deductions_association_id', sa.Integer(), nullable=False),
    sa.Column('general_statement_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deductions_association_id'], ['deductions_association.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['earnings_association_id'], ['earnings_association.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['general_statement_info_id'], ['general_statement_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('earnings_association_id', 'deductions_association_id', 'general_statement_info_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings_deductions_association')
    op.drop_table('deductions_association')
    op.drop_table('earnings_association')
    op.drop_table('ytd_deductions')
    op.drop_table('ytd_earnings')
    op.drop_table('general_statement_info')
    op.drop_table('deductions')
    op.drop_table('earnings')
    ### end Alembic commands ###
