"""first bank database model

Revision ID: 3b26e8cf4d
Revises: None
Create Date: 2014-11-23 19:42:05.258967

"""

# revision identifiers, used by Alembic.
revision = '3b26e8cf4d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
