#%RAML 0.8
title: API documentation for work statement
baseUri: http://bank-dev:1234/
version: v1

schemas:
  - general_statement_info: |
      {
        "$schema":"http://json-schema.org/draft-03/schema",
        "type":"object",
        "description":"The conanical general statement representation",
        "properties":{
          "rate":{
            "type":"float",
            "required":true
          },
          "hours":{
            "type":"float",
            "required":true
          },
          "company_name":{
            "type":"string",
            "required":true
          },
          "payment_date":{
            "type":"datetime",
            "required":true
          }
        }
      }

resourceTypes:
  - general_statement_info:
      post:
        description: For submiting the hours, rate, payment date, and company name
        body:
          application/json:
            schema: general_statement_info

/work_statement:
  description: home page for the work statement
  get:
    description: return the list of years and companies
    responses:
      200:
        description: OK
        body:
          application/json:
            example: |
              {
                "data":{
                  "years":["2011","2012","2013","2014"],
                  "companies":["Longbow Advantage","Nuance Communications Inc."]
                }
              }
      500:
        description: Request was not successfully processed
        body:
          application/json:
            example: |
              {
                "error":{
                  "message":"Internal Server Error: Unable to get list of companies and years"
                }
              }

/work_statement/general_statement_info:
  description: For submiting the hours, rate, payment date, and company name
  type: general_statement_info
  post:
    body:
      application/json:
         example: |
           {
            "rate":23.00,
            "hours":80.00,
            "company_name":"Nuance Communications Inc.",
            "payment_date":"2014-05-20"
           }
    responses:
      201:
        description: OK
      400:
        description: If the input format does not respect the requirements
        body:
          application/json:
            example: |
              {
                "error":{
                  "message":"Bad Request"
                }
              }
      500:
        description: Request was not successfully processed
        body:
          application/json:
            example: |
              {
                "error":{
                  "message":"Internal Server Error: Unable to add general statement info"
                }
              }