"""first database

Revision ID: 1a20c20db1b
Revises: 
Create Date: 2014-12-09 00:26:38.901808

"""

# revision identifiers, used by Alembic.
revision = '1a20c20db1b'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('government_pension', sa.Float(), nullable=False),
    sa.Column('federal_tax', sa.Float(), nullable=False),
    sa.Column('qpip', sa.Float(), nullable=False),
    sa.Column('ei_contribution', sa.Float(), nullable=False),
    sa.Column('provencial_tax', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_statement_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ytd_deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('government_pension', sa.Float(), nullable=False),
    sa.Column('federal_tax', sa.Float(), nullable=False),
    sa.Column('qpip', sa.Float(), nullable=False),
    sa.Column('ei_contribution', sa.Float(), nullable=False),
    sa.Column('provencial_tax', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ytd_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('less_taxable_benefits', sa.Float(), nullable=False),
    sa.Column('total_gross', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_ytd_id', sa.Integer(), nullable=True),
    sa.Column('earnings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['earnings_id'], ['earnings.id'], ),
    sa.ForeignKeyConstraint(['earnings_ytd_id'], ['ytd_earnings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deductions_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deductions_ytd_id', sa.Integer(), nullable=True),
    sa.Column('deductions_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deductions_id'], ['deductions.id'], ),
    sa.ForeignKeyConstraint(['deductions_ytd_id'], ['ytd_deductions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings_deductions_associations',
    sa.Column('earnings_association_id', sa.Integer(), nullable=False),
    sa.Column('deductions_association_id', sa.Integer(), nullable=False),
    sa.Column('general_statement_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deductions_association_id'], ['deductions_associations.id'], ),
    sa.ForeignKeyConstraint(['earnings_association_id'], ['earnings_associations.id'], ),
    sa.ForeignKeyConstraint(['general_statement_info_id'], ['general_statement_information.id'], ),
    sa.PrimaryKeyConstraint('earnings_association_id', 'deductions_association_id', 'general_statement_info_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings_deductions_associations')
    op.drop_table('deductions_associations')
    op.drop_table('earnings_associations')
    op.drop_table('earnings')
    op.drop_table('ytd_earnings')
    op.drop_table('ytd_deductions')
    op.drop_table('general_statement_information')
    op.drop_table('deductions')
    ### end Alembic commands ###
